### ISSUE TITLE
[question] docker-compose not working

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan-io.github.io#223]
Trying to render the blog on Windows with Docker:

First, updated the docker-compose to:
```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index c77acba..7b3f7e3 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,8 +1,9 @@
-jekyll:
-    image: jekyll/jekyll:pages
-    command: /bin/sh -c /srv/jekyll/serve.sh
-    ports:
-        - 4000:4000
-    volumes:
-        - .:/srv/jekyll
+services:
+    jekyll:
+        image: jekyll/jekyll:latest
+        command: /bin/sh -c /srv/jekyll/serve.sh
+        ports:
+            - 4000:4000
+        volumes:
+            - .:/srv/jekyll
```

But still obtaining
```
λ docker-compose up                                                                                                                                           
[+] Running 1/0                                                                                                                                               
 - Container conan-iogithubio-jekyll-1  Created                                                                                                          0.0s 
Attaching to conan-iogithubio-jekyll-1                                                                                                                        
conan-iogithubio-jekyll-1  | ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]                                                               
conan-iogithubio-jekyll-1  | Configuration file: /srv/jekyll/_config.yml                                                                                      
conan-iogithubio-jekyll-1  |             Source: /srv/jekyll                                                                                                  
conan-iogithubio-jekyll-1  |        Destination: /srv/jekyll/_site                                                                                            
conan-iogithubio-jekyll-1  |  Incremental build: disabled. Enable with --incremental                                                                          
conan-iogithubio-jekyll-1  |       Generating...                                                                                                              
conan-iogithubio-jekyll-1  |                     done in 11.785 seconds.                                                                                      
conan-iogithubio-jekyll-1  |                     Auto-regeneration may not work on some Windows versions.                                                     
conan-iogithubio-jekyll-1  |                     Please see: https://github.com/Microsoft/BashOnWindows/issues/216                                            
conan-iogithubio-jekyll-1  |                     If it does not work, please upgrade Bash on Windows or run Jekyll with --no-watch.                           
conan-iogithubio-jekyll-1  |  Auto-regeneration: enabled for '/srv/jekyll'                                                                                    
conan-iogithubio-jekyll-1  |                     ------------------------------------------------                                                             
conan-iogithubio-jekyll-1  |       Jekyll 4.2.2   Please append `--trace` to the `serve` command                                                              
conan-iogithubio-jekyll-1  |                      for any additional information or backtrace.                                                                
conan-iogithubio-jekyll-1  |                     ------------------------------------------------                                                             
conan-iogithubio-jekyll-1  | <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- webr
ick (LoadError)                                                                                                                                               
conan-iogithubio-jekyll-1  |    from <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'                       
conan-iogithubio-jekyll-1  |    from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'                                  
conan-iogithubio-jekyll-1  |    from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:179:in `require_relative'                                        
conan-iogithubio-jekyll-1  |    from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:179:in `setup'                                                   
conan-iogithubio-jekyll-1  |    from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:100:in `process'                                                 
conan-iogithubio-jekyll-1  |    from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'                             
conan-iogithubio-jekyll-1  |    from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `each'                                                            
conan-iogithubio-jekyll-1  |    from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'                                      
conan-iogithubio-jekyll-1  |    from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'                    
conan-iogithubio-jekyll-1  |    from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'                                         
conan-iogithubio-jekyll-1  |    from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'                                                     
conan-iogithubio-jekyll-1  |    from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'                                                  
conan-iogithubio-jekyll-1  |    from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'                                                        
conan-iogithubio-jekyll-1  |    from /usr/gem/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'                                                           
conan-iogithubio-jekyll-1  |    from /usr/gem/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'                                                           
conan-iogithubio-jekyll-1  |    from /usr/gem/bin/jekyll:25:in `load'                                                                                         
conan-iogithubio-jekyll-1  |    from /usr/gem/bin/jekyll:25:in `<main>'                                                                                       
conan-iogithubio-jekyll-1 exited with code 1                                                                                                                  
```

Am I missing something? What are you using to render the blog @uilianries @prince-chrismc ?

**Comment by prince-chrismc** [comment]
Linux and MacOS have really easy ruby installs, haven't tried this on Windows

**Comment by memsharded** [comment]
Yep, but the ruby install happens inside the docker, so it shouldn't be an issue?

**Comment by czoido** [comment]
I use: 

```
docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll  -it -p 4000:4000 jekyll/jekyll:3.5 jekyll serve --future
```

Maybe that works for you

**Comment by memsharded** [comment]
Yes, that works, maybe it is related to the specific image version. Many thanks!

**Comment by uilianries** [comment]
> I don't use docker :) I just use the system apt or brew ones

Traitor! You should burn! 😝
